language: node_js
dist: trusty
sudo: required
node_js:
 - "8"

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

before_deploy:
  - npm run prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master

addons:
  chrome: stable